# Generated by Django 4.1.7 on 2023-03-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_user_wathclist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='wathclist',
            new_name='watchlist',
        ),
    ]
